import { ParsedSkill } from "./skill.js";

const BEGIN_MARKER = "<!-- claude-skills:begin -->";
const END_MARKER = "<!-- claude-skills:end -->";

function buildFullBlock(skills: ParsedSkill[]): string {
  const lines: string[] = [
    BEGIN_MARKER,
    "<!-- Generated by claude-skills — do not edit this block manually -->",
    "## Active Skills",
    "",
  ];

  for (const skill of skills) {
    const version = skill.meta.version !== "0.0.0" ? ` (v${skill.meta.version})` : "";
    lines.push(`### ${skill.meta.name}${version}`);
    lines.push(skill.meta.description);
    lines.push("");
    lines.push(skill.content);
    lines.push("");
  }

  lines.push(END_MARKER);
  return lines.join("\n");
}

function buildCatalogBlock(skills: ParsedSkill[]): string {
  const lines: string[] = [
    BEGIN_MARKER,
    "<!-- Generated by claude-skills — do not edit this block manually -->",
    "## Available Skills",
    "",
    "| Skill | Command | Description |",
    "|---|---|---|",
  ];

  for (const skill of skills) {
    const cmd = skill.meta.command ? `/${skill.meta.command}` : skill.meta.name;
    const desc = skill.meta.description.replace(/\n/g, " ").slice(0, 120);
    lines.push(`| ${skill.meta.name} | ${cmd} | ${desc} |`);
  }

  lines.push("");
  lines.push(
    "Use the slash command to invoke a skill. Full skill instructions are loaded on invocation."
  );
  lines.push(END_MARKER);
  return lines.join("\n");
}

export function injectSkills(
  existingContent: string,
  skills: ParsedSkill[],
  mode: "full" | "catalog"
): string {
  const block =
    mode === "catalog" ? buildCatalogBlock(skills) : buildFullBlock(skills);

  if (skills.length === 0) {
    // Remove existing block if no active skills
    return removeBlock(existingContent);
  }

  const beginIdx = existingContent.indexOf(BEGIN_MARKER);
  const endIdx = existingContent.indexOf(END_MARKER);

  if (beginIdx !== -1 && endIdx !== -1) {
    // Replace existing block
    const before = existingContent.slice(0, beginIdx);
    const after = existingContent.slice(endIdx + END_MARKER.length);
    return before + block + after;
  }

  // Append block
  if (existingContent.trim()) {
    return existingContent.trimEnd() + "\n\n" + block + "\n";
  }
  return block + "\n";
}

function removeBlock(content: string): string {
  const beginIdx = content.indexOf(BEGIN_MARKER);
  const endIdx = content.indexOf(END_MARKER);

  if (beginIdx === -1 || endIdx === -1) return content;

  const before = content.slice(0, beginIdx);
  const after = content.slice(endIdx + END_MARKER.length);
  return (before + after).replace(/\n{3,}/g, "\n\n").trim() + "\n";
}
